import { IKeyLayout } from '../../interface/IKeyLayout';

const keyLayoutRu: IKeyLayout = {
  Backquote: { classHand: 'lhand4', btnName: 'Ё', normal: 'ё', alt: 'Ё' },
  Digit1: { classHand: 'lhand4', btnName: '1<sup>!</sup>', normal: '1', alt: '!' },
  Digit2: { classHand: 'lhand3', btnName: '2<sup>"</sup>', normal: '2', alt: '"' },
  Digit3: { classHand: 'lhand2', btnName: '3<sup>№</sup>', normal: '3', alt: '№' },
  Digit4: { classHand: 'lhand1', btnName: '4<sup>;</sup>', normal: '4', alt: ';' },
  Digit5: { classHand: 'lhand1', btnName: '5<sup>%</sup>', normal: '5', alt: '%' },
  Digit6: { classHand: 'rhand1', btnName: '6<sup>:</sup>', normal: '6', alt: ':' },
  Digit7: { classHand: 'rhand1', btnName: '7<sup>?</sup>', normal: '7', alt: '?' },
  Digit8: { classHand: 'rhand2', btnName: '8<sup>*</sup>', normal: '8', alt: '*' },
  Digit9: { classHand: 'rhand3', btnName: '9<sup>(</sup>', normal: '9', alt: '(' },
  Digit0: { classHand: 'rhand4', btnName: '0<sup>)</sup>', normal: '0', alt: ')' },
  Minus: { classHand: 'rhand4', btnName: '-<sup>_</sup>', normal: '-', alt: '_' },
  Equal: { classHand: 'rhand4', btnName: '=<sup>+</sup>', normal: '=', alt: '+' },
  Backspace: { classHand: 'rhand4', btnName: '⇦', normal: '', alt: '' },
  KeyQ: { classHand: 'lhand4', btnName: 'Й', normal: 'й', alt: 'Й' },
  KeyW: { classHand: 'lhand3', btnName: 'Ц', normal: 'ц', alt: 'Ц' },
  KeyE: { classHand: 'lhand2', btnName: 'У', normal: 'у', alt: 'У' },
  KeyR: { classHand: 'lhand1', btnName: 'К', normal: 'к', alt: 'К' },
  KeyT: { classHand: 'lhand1', btnName: 'Е', normal: 'е', alt: 'Е' },
  KeyY: { classHand: 'rhand1', btnName: 'Н', normal: 'н', alt: 'Н' },
  KeyU: { classHand: 'rhand1', btnName: 'Г', normal: 'г', alt: 'Г' },
  KeyI: { classHand: 'rhand2', btnName: 'Ш', normal: 'ш', alt: 'Ш' },
  KeyO: { classHand: 'rhand3', btnName: 'Щ', normal: 'щ', alt: 'Щ' },
  KeyP: { classHand: 'rhand4', btnName: 'З', normal: 'з', alt: 'З' },
  BracketLeft: { classHand: 'rhand4', btnName: 'Х', normal: 'х', alt: 'Х' },
  BracketRight: { classHand: 'rhand4', btnName: 'Ъ', normal: 'ъ', alt: 'Ъ' },
  CapsLock: { classHand: 'rhand4', btnName: 'caps', normal: '', alt: '' },
  KeyA: { classHand: 'lhand4', btnName: 'Ф', normal: 'ф', alt: 'Ф' },
  KeyS: { classHand: 'lhand3', btnName: 'Ы', normal: 'ы', alt: 'Ы' },
  KeyD: { classHand: 'lhand2', btnName: 'В', normal: 'в', alt: 'В' },
  KeyF: { classHand: 'lhand1', btnName: 'А', normal: 'а', alt: 'А' },
  KeyG: { classHand: 'lhand1', btnName: 'П', normal: 'п', alt: 'П' },
  KeyH: { classHand: 'rhand1', btnName: 'Р', normal: 'р', alt: 'Р' },
  KeyJ: { classHand: 'rhand1', btnName: 'О', normal: 'о', alt: 'О' },
  KeyK: { classHand: 'rhand2', btnName: 'Л', normal: 'л', alt: 'Л' },
  KeyL: { classHand: 'rhand3', btnName: 'Д', normal: 'д', alt: 'Д' },
  Semicolon: { classHand: 'rhand4', btnName: 'Ж', normal: 'ж', alt: 'Ж' },
  Quote: { classHand: 'rhand4', btnName: 'Э', normal: 'э', alt: 'Э' },
  Enter: { classHand: 'lhand4', btnName: 'enter', normal: '', alt: '' },
  ShiftLeft: { classHand: 'lhand4', btnName: 'shift', normal: '', alt: '' },
  KeyZ: { classHand: 'lhand4', btnName: 'Я', normal: 'я', alt: 'Я' },
  KeyX: { classHand: 'lhand3', btnName: 'Ч', normal: 'ч', alt: 'Ч' },
  KeyC: { classHand: 'lhand2', btnName: 'С', normal: 'с', alt: 'С' },
  KeyV: { classHand: 'lhand1', btnName: 'М', normal: 'м', alt: 'М' },
  KeyB: { classHand: 'lhand1', btnName: 'И', normal: 'и', alt: 'И' },
  KeyN: { classHand: 'rhand1', btnName: 'Т', normal: 'т', alt: 'Т' },
  KeyM: { classHand: 'rhand1', btnName: 'Ь', normal: 'ь', alt: 'Ь' },
  Comma: { classHand: 'rhand2', btnName: 'Б', normal: 'б', alt: 'Б' },
  Period: { classHand: 'rhand3', btnName: 'Ю', normal: 'ю', alt: 'Ю' },
  Slash: { classHand: 'rhand4', btnName: '.<sup>,</sup>', normal: '.', alt: ',' },
  ShiftRight: { classHand: 'rhand4', btnName: 'shift', normal: '', alt: '' },
  Space: { classHand: 'rhand0', btnName: ' ', normal: ' ', alt: '' },
};

export default keyLayoutRu;
