import { IKeyLayout } from '../../interface/IKeyLayout';

const keyLayoutEn: IKeyLayout = {
  Backquote: { classHand: 'lhand4', btnName: '<sub>`</sub><sup>~</sup>', normal: '`', alt: '!' },
  Digit1: { classHand: 'lhand4', btnName: '1<sup>!</sup>', normal: '1', alt: '!' },
  Digit2: { classHand: 'lhand3', btnName: '2<sup>@</sup>', normal: '2', alt: '@' },
  Digit3: { classHand: 'lhand2', btnName: '3<sup>#</sup>', normal: '3', alt: '#' },
  Digit4: { classHand: 'lhand1', btnName: '4<sup>$</sup>', normal: '4', alt: '$' },
  Digit5: { classHand: 'lhand1', btnName: '5<sup>%</sup>', normal: '5', alt: '%' },
  Digit6: { classHand: 'rhand1', btnName: '6<sup>^</sup>', normal: '6', alt: '^' },
  Digit7: { classHand: 'rhand1', btnName: '7<sup>&</sup>', normal: '7', alt: '&' },
  Digit8: { classHand: 'rhand2', btnName: '8<sup>*</sup>', normal: '8', alt: '*' },
  Digit9: { classHand: 'rhand3', btnName: '9<sup>(</sup>', normal: '9', alt: '(' },
  Digit0: { classHand: 'rhand4', btnName: '0<sup>)</sup>', normal: '0', alt: ')' },
  Minus: { classHand: 'rhand4', btnName: '-<sup>_</sup>', normal: '-', alt: '_' },
  Equal: { classHand: 'rhand4', btnName: '=<sup>+</sup>', normal: '=', alt: '+' },
  Backspace: { classHand: 'rhand4', btnName: '⇦', normal: '', alt: '' },
  KeyQ: { classHand: 'lhand4', btnName: 'Q', normal: 'q', alt: 'Q' },
  KeyW: { classHand: 'lhand3', btnName: 'W', normal: 'w', alt: 'W' },
  KeyE: { classHand: 'lhand2', btnName: 'E', normal: 'e', alt: 'E' },
  KeyR: { classHand: 'lhand1', btnName: 'R', normal: 'r', alt: 'R' },
  KeyT: { classHand: 'lhand1', btnName: 'T', normal: 't', alt: 'T' },
  KeyY: { classHand: 'rhand1', btnName: 'Y', normal: 'y', alt: 'Y' },
  KeyU: { classHand: 'rhand1', btnName: 'U', normal: 'u', alt: 'U' },
  KeyI: { classHand: 'rhand2', btnName: 'I', normal: 'i', alt: 'I' },
  KeyO: { classHand: 'rhand3', btnName: 'O', normal: 'o', alt: 'O' },
  KeyP: { classHand: 'rhand4', btnName: 'P', normal: 'p', alt: 'P' },
  BracketLeft: { classHand: 'rhand4', btnName: '[<sup>{</sup>', normal: '[', alt: '{' },
  BracketRight: { classHand: 'rhand4', btnName: ']<sup>}</sup>', normal: ']', alt: '}' },
  CapsLock: { classHand: 'lhand4', btnName: 'caps', normal: '', alt: '' },
  KeyA: { classHand: 'lhand4', btnName: 'A', normal: 'a', alt: 'A' },
  KeyS: { classHand: 'lhand3', btnName: 'S', normal: 's', alt: 'S' },
  KeyD: { classHand: 'lhand2', btnName: 'D', normal: 'd', alt: 'D' },
  KeyF: { classHand: 'lhand1', btnName: 'F', normal: 'f', alt: 'F' },
  KeyG: { classHand: 'lhand1', btnName: 'G', normal: 'g', alt: 'G' },
  KeyH: { classHand: 'rhand1', btnName: 'H', normal: 'h', alt: 'H' },
  KeyJ: { classHand: 'rhand1', btnName: 'J', normal: 'j', alt: 'J' },
  KeyK: { classHand: 'rhand2', btnName: 'K', normal: 'k', alt: 'K' },
  KeyL: { classHand: 'rhand3', btnName: 'L', normal: 'l', alt: 'L' },
  Semicolon: { classHand: 'rhand4', btnName: ';<sup>:</sup>', normal: ';', alt: ':' },
  Quote: { classHand: 'rhand4', btnName: `'<sup>"</sup>`, normal: `'`, alt: '"' },
  Enter: { classHand: 'rhand4', btnName: 'enter', normal: '', alt: '' },
  ShiftLeft: { classHand: 'rhand4', btnName: 'shift', normal: '', alt: '' },
  KeyZ: { classHand: 'lhand4', btnName: 'Z', normal: 'z', alt: 'Z' },
  KeyX: { classHand: 'lhand3', btnName: 'X', normal: 'x', alt: 'X' },
  KeyC: { classHand: 'lhand2', btnName: 'C', normal: 'c', alt: 'C' },
  KeyV: { classHand: 'lhand1', btnName: 'V', normal: 'v', alt: 'V' },
  KeyB: { classHand: 'lhand1', btnName: 'B', normal: 'b', alt: 'B' },
  KeyN: { classHand: 'rhand1', btnName: 'N', normal: 'n', alt: 'N' },
  KeyM: { classHand: 'rhand1', btnName: 'M', normal: 'm', alt: 'M' },
  Comma: { classHand: 'rhand2', btnName: ',<sup><</sup>', normal: ',', alt: '<' },
  Period: { classHand: 'rhand3', btnName: '.<sup>></sup>', normal: '.', alt: '>' },
  Slash: { classHand: 'rhand4', btnName: '/<sup>?</sup>', normal: '/', alt: '?' },
  ShiftRight: { classHand: 'rhand4', btnName: 'shift', normal: '', alt: '' },
  Space: { classHand: 'rhand0', btnName: ' ', normal: ' ', alt: '' },
};

export default keyLayoutEn;
